### ISSUE TITLE
Item on spawn

### ISSUE THREAD

**Issue by RexTheKid** [DracoDragon88/gcphone_vrp#15]
er det muligt at gøre så man spawner med den så man ikke skal hen og købe den eller andet :D

**Comment by DracoDragon88** [comment]
gcphone/client/client.lua
local useAPhone = true

true = med item
false = uden item

**Comment by RexTheKid** [comment]
Mange tak det virker :D. Men skal man gøre noget for at få den til at connect med ingame jobs kan nemelig ikke få service calls til at virke? når jeg fx ringer til taxa får de ikke noti. (normale beskeder virker)

**Comment by DracoDragon88** [comment]
du skal konfigurer service calls i 
```
gcphone/html/static/config/config.json
under "serviceCall"
```
Nummeret skal være det samme som i 
```
vRP/vrp/cfg/phone.lua
under cfg.services
```

**Comment by RexTheKid** [comment]
det burde da også rigth?


  "serviceCall": [
    {
      "display": "Politi",
      "icon": "/html/static/img/icons_app/politi.png",
      "subMenu": [
        {
          "title": "Send en besked",
          "eventName": "vrp_addons_gcphone:call",
          "type": {
            "number": "Politi"

cfg.services = {
  ["politi"] = {
    blipid = 304,
    blipcolor = 38,
    alert_time = 300, -- 5 minutes
    alert_permission = "police.service",
    alert_notify = "~r~Central alarmen:~n~~s~",
    notify = "~b~Du har ringet til politiet.",
    answer_notify = "~b~Politiet er på vej."

**Comment by DracoDragon88** [comment]
Husk at LUA er Caps sensitiv
så hvis 
```
cfg.services = {
["politi"] = {
...
```
er men lille skrift skal 
```
"type": {
"number": "politi"
```
også være men lille skrift
