### ISSUE TITLE
app.js formattet

### ISSUE THREAD

**Issue by Kh4zy** [DracoDragon88/gcphone_vrp#19]
Hi Draco. Is it possible upload a formattet app.js so its readable? The file is just a oneline code :/

**Comment by DracoDragon88** [comment]
I have only conveted the resource to tho old vrp. But you can try the orginal git here: https://github.com/N3MTV/gcphone i have not edited the app.js file

**Comment by Kh4zy** [comment]
> I have only conveted the resource to tho old vrp. But you can try the orginal git here: https://github.com/N3MTV/gcphone i have not edited the app.js file

Ahh okay. The source from the original is minified aswell but I have resolved it
