### ISSUE TITLE
GCPhone problem

### ISSUE THREAD

**Issue by husemoen06** [DracoDragon88/gcphone_vrp#2]
**jeg har din gcphone men banken virker ikke kan du hjælpe mig med at få den til at virke** @DracoDragon88

**Comment by DracoDragon88** [comment]
Jeg er update bank.lua til simple banking resource
se update #https://github.com/DracoDragon88/gcphone_vrp/commit/c66de4fa7ccb765be6cec126b57df49382962f71

hvis dette ikke virker skal du i dit bank script tilføje 
`TriggerClientEvent('banking:updateBalance', source, bankbalance)`
for at sende balancen til gcphone...
