### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by msnrick** [DracoDragon88/gcphone_vrp#20]
I am getting error "ingen mobil", when press f2, get that error... do u know what is happening?
I am using vrp dunkos vRP pack

**Comment by msnrick** [comment]
And can I put that item on a store to users can buy the phone from a store?

**Comment by msnrick** [comment]
The phone only works when I give me the item on admin command

**Comment by DracoDragon88** [comment]
It's not an error its danish for "No Phone"
but you can disable the item check in gcphone/client/client.lua:16
