### ISSUE TITLE
vrpex version

### ISSUE THREAD

**Issue by edmoreirajr** [DracoDragon88/gcphone_vrp#21]
Would this vrp version work on vrpex? I tried installing it but I'm getting a common error on esx, which says that '@receive' cannot be null when running this line:

`local Query = "INSERT INTO phone_messages (`transmitter`,`receiver`,`message`,`isRead`,`owner`) VALUES(@transmitter,@receiver,@message,@isRead,@owner);"`

**Comment by DracoDragon88** [comment]
I'm not sure if et works on vrpex...
