### ISSUE TITLE
Sql error

### ISSUE THREAD

**Issue by gdsasa** [DracoDragon88/gcphone_vrp#23]
Error de SQL (1064): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '�FF-- ---------------------------------------------------------- Host :    ...' at line 1uery
Im getting that error in Heidi sql when running base.sql

**Comment by DracoDragon88** [comment]
It is because your MariaDB version is newer then the version used to make the .sql files. But you can remove all the comment out sections and then it should work, or use https://github.com/DracoDragon88/gcphone_vrp/blob/v3.0/AllInOne.sql

**Comment by gdsasa** [comment]
same error with that https://github.com/DracoDragon88/gcphone_vrp/blob/v3.0/AllInOne.sql

**Comment by DracoDragon88** [comment]
I dont have any errors when I import the sql files in my MariaDB 10.4.14

**Comment by gdsasa** [comment]
Im going to install that version
