### ISSUE TITLE
Hello Draco, I get this error when i open the phone ingame everything works and no lag 

### ISSUE THREAD

**Issue by SwoxiTV** [DracoDragon88/gcphone_vrp#3]
https://gyazo.com/d283a20e9e330fc860bcd8c9480786ac

**Comment by DracoDragon88** [comment]
Do you use vRPex or vRP/dunko

**Comment by SwoxiTV** [comment]
dunko

**Comment by SwoxiTV** [comment]
Any idea?

**Comment by DracoDragon88** [comment]
Sorry for the delay. 
In the picture you sent, I can't see the function where the error has occurred in.
but the error is a vrp proxy error... 
so is probably one of the vRP connections that is a problem.
you can search for VRP. In the server files and make sure all of them is sending to the vrp proxy
I tried to set up a quick vRP server and the gcphone is working fine for me. just make sure you haven't changed any after names of the folders.

**Comment by NexzTV** [comment]
The error is in vrp itself - basic_phone.lua

**Comment by SwoxiTV** [comment]
fixed it along time ago forgot to type here tho sry
