### ISSUE TITLE
[SOLVED]Help Me?

### ISSUE THREAD

**Issue by TheyCallMeAle** [DracoDragon88/gcphone_vrp#4]
Hi, I use dunkovrp, the only problem I found that when I edit words from one translation to another they don't work.

Can you tell me why?

**Comment by DracoDragon88** [comment]
Most of the translation is in the app.js but it is allsow the main funktions of the Phone so if you make an error in it the Phone will not work right now the Phone is in danish and some in france I haven't have the time to translate it to english yet.

**Comment by TheyCallMeAle** [comment]
Thank you
