### ISSUE TITLE
Tidspunkter i beskeder?

### ISSUE THREAD

**Issue by NexzTV** [DracoDragon88/gcphone_vrp#5]
Hey

Jeg har et problem

Når folk og f.eks jeg sender beskeder opdatere tidspunkterne ikke sig selv? Efter et par dage skriver den 6-7 timer og den bliver ved "Lige nu" og samme inde i "Opkald"

https://i.gyazo.com/7e3c93b4c799df0471da0e6f7794d74f.png

Er det noget du ved eller kan se på? :/ Jeg ved ikke om det er database problem fordi den fungere fint

**Comment by DracoDragon88** [comment]
Skal se om jeg kan finde fejlen

**Comment by NexzTV** [comment]
Jeg kan ikke finde nogen årsag til dette - Har du fundet ud af noget?

**Comment by DracoDragon88** [comment]
Jeg her testet min og der er ikke noget i vejen med den så tror det nå være det du har oversat eller din mysqldatabase... jeg vil update app.js med det jeg har oversat
#https://github.com/DracoDragon88/gcphone_vrp/commit/6380f010431ebd2fe02398b748bb1ecc94c607a6

**Comment by NexzTV** [comment]
Vildt underligt. I databasen skriver den det rigtige tidspunkt men i telefonen bliver den ved med "Lige nu" indtil der f.eks er gået 2 dage? Jeg bruger xampp med MariaDB - Kan det være derfor? Det burde det nemlig ikke og MySQL og FiveM køre på samme maskine

**Comment by DracoDragon88** [comment]
Jeg ved ikke hvad problemet skulle være ellers jeg har prøvt og se om den gør det på min test server men der virker den fint...

**Comment by NexzTV** [comment]
Jeg fandt problemet. Jeg havde MariaDB installeret og det SKAL åbenbart være MySQL. Så den virker perfekt nu :)
