### ISSUE TITLE
help?

### ISSUE THREAD

**Issue by TheyCallMeAle** [DracoDragon88/gcphone_vrp#7]
Hi, can you do that when a player enters the server it doesn't have to "buy" phone items to get, and just that when he goes in he does F2 without buying it?

**Comment by DracoDragon88** [comment]
If you won't to skip the phone item just replace
`TriggerServerEvent('gcPhone:doIhaveAphone')`
with
`TooglePhone()`
in gcphone/client/client.lua line 149

**Comment by TheyCallMeAle** [comment]
Thanks
