### ISSUE TITLE
Don't listen to the other person during the call

### ISSUE THREAD

**Issue by AdrianQ1404** [DracoDragon88/gcphone_vrp#8]
Hi, me and my friend are developing a vRP server and we put this ghcphone version but we had a problem int call with a player and we did not listen our voices in call.
We tries change the code in :
vrp/cfg/client.lua
-- set to true to disable the default voice chat and use vRP voip instead (world channel) 
cfg.vrp_voip = true
cfg.vrp_voip = false
true or false don't work
----------------------
vrp]\vrp\client\base.lua
at the end of the file, comment on this line: NetworkSetTalkerProximity(proximity+0.0001)
comment and uncomment this line
-------------------------------
 "useWebRTCVocal": true,
  "RTCConfig": {
    "iceServers": [{
      "urls": ["stun:stun.l.google.com:19302", "stun:stun1.l.google.com:19302", "stun:stun2.l.google.com:19302"]
    }]
  },
"RTCConfig": {
    "iceServers": [{
      "urls": ["turn:gannon.ovh"],
      "username": "jojo",
      "credential": "pass"
    }]
  },
switching this urls using the origial voip url
-----------------------
in gcphone/client/client.lua
local USE_RTC = true
local USE_RTC = false
true or false don't work
--------------------------
We wait a answer thank's

**Comment by DracoDragon88** [comment]
What version of vRP are you using vRPex or vRP/dunko
If you set "useWebRTCVocal" to false you use the GTA voice channel Else you have to set up a turn server/WEBRTC

**Comment by rafaeltortella** [comment]
Yoo Draco i'm his friend =D...

We are using VRp from https://github.com/ImagicTheCat/vRP and we are using the last realese avaiable https://github.com/ImagicTheCat/vRP/releases called "Before vRP 2"

For the Voip system we are using: https://github.com/SSPU1W/Kodakvoip 
with style:  https://github.com/SSPU1W/FamilyRP-Styled-Voice

And as he said, we have tryed all this configurations above

------------------------

vrp/cfg/client.lua
-- we tried set this to TRUE and to FALSE
cfg.vrp_voip = true
cfg.vrp_voip = false

------------------------

[vrp]\vrp\client\base.lua
comment and uncomment this line
"at the end of the file, comment on this line: NetworkSetTalkerProximity(proximity+0.0001)"

------------------------

"useWebRTCVocal": true,
"RTCConfig": {
"iceServers": [{
"urls": ["stun:stun.l.google.com:19302", "stun:stun1.l.google.com:19302", "stun:stun2.l.google.com:19302"]
}]
},
"RTCConfig": {
"iceServers": [{
"urls": ["turn:gannon.ovh"],
"username": "jojo",
"credential": "pass"
}]
},
switching this urls using the origial voip url

------------------------

in gcphone/client/client.lua
local USE_RTC = true
local USE_RTC = false
true or false don't work

------------------------


And i think thats all... the gcphone work, contact messages and etc... the call work too but we can not listen each other... and only speaking using the Kodakvoip system we can listem each other...

What do you think we should do? =((
And also we should use GTA voip or our own voip system? whats your opinion?
Thanks for your time!

**Comment by DracoDragon88** [comment]
You have enabled "useWebRTCVocal": true,
sow have til configure it.
you only need one config like.
`"RTCConfig": {
"iceServers": [{
"urls": ["turn:gannon.ovh"],
"username": "jojo",
"credential": "pass"
}]
},`
I don't know if you can use googles servers...
Those I know that that use it it is using a turn and not a stun but thay had to set one up them self.
but you can set 
`"useWebRTCVocal": false,`
and then it should work but you are limited to the GTA voice channels so if you have more than 32 slots you might get some problems,
else if you're running a dedicated server you can set up a turn server yourself.

**Comment by rafaeltortella** [comment]
Did you have any link or tutorial to set up a RTC server for vrp?

**Comment by DracoDragon88** [comment]
WebRTC is a HTTP voip 
I don't know much about it but try this maybe 
https://easyrtc.com/docs/easyrtc_gettingStarted.php

**Comment by rafaeltortella** [comment]
And you suggest to use RTC from GTA or create my own? 
My server should be only for 32 slots

Btw thanks for the awesers, tonight i will test again and send to you a feed back.
